name: Daily YouTube Upload - Categories

on:
  # 12:30 UTC = 18:00 IST. IST is UTC + 5:30 hours
  schedule:
    # Weekdays: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 1-5'
    # Weekends: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 6,0'
  workflow_dispatch: # Allow manual runs too

jobs:
  upload:
    # Option 1: Use container (FASTEST)
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
      options: --user root

    steps:
    - name: Print Timestamp
      run: date -u

    - name: Checkout repo
      uses: actions/checkout@v4  # Updated to v4

    # Skip Python setup when using container
    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.12'

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y ffmpeg git curl
        rm -rf /var/lib/apt/lists/*

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install --no-cache-dir -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4  # Updated to v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup environment and secrets
      run: |
        echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env
        echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl
        echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

    - name: Run upload script
      run: python main.py categories