name: Daily YouTube Upload - Categories US

on:
  # For USA context, 1:00 PM ET → 10:30 PM IST (same day). ET is UTC - 4:00 hours
  schedule:
    # Weekdays: 12:00, 19:00 ET
    - cron: '0 16,23 * * 1-5'
    # Weekends: 09:00, 15:00 ET
    - cron: '0 13,19 * * 6,0'
  workflow_dispatch:  # Allow manual runs too

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

#      - name: Install Hindi (Devanagari) fonts
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-unhinted

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Export secret to .env file
        run: echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env

      - name: Restore token.pkl
        run: |
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl

      - name: Write client_secrets.json
        run: |
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Run upload script
        run: python main.py categories us
