name: Daily YouTube Upload - Categories

on:
  # 12:30 UTC = 18:00 IST. IST is UTC + 5:30 hours
  schedule:
    # Weekdays: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 1-5'
    # Weekends: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 6,0'
  workflow_dispatch: # Allow manual runs too

# Prevent multiple workflow runs from overlapping
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    # Use a container with Python and FFmpeg pre-installed to save startup time
    container:
      image: jrottenberg/ffmpeg:4.4-ubuntu

    # Set a timeout to ensure jobs don't run indefinitely if something hangs
    timeout-minutes: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # Built-in pip caching - much simpler than manual caching

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            ca-certificates \
            git \
            wget \
            curl

      - name: Install Python dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup environment and secrets
        run: |
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Run upload script
        run: python main.py categories
