name: Daily YouTube Upload - Categories

on:
  # 12:30 UTC = 18:00 IST. IST is UTC + 5:30 hours
  schedule:
    # Weekdays: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 1-5'
    # Weekends: 6 AM, 8 AM IST
    - cron: '30 0,2 * * 6,0'
  workflow_dispatch: # Allow manual runs too

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

#      - name: Install FFmpeg
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y ffmpeg

      - name: Setup pip cache directory
        run: mkdir -p ~/.cache/pip

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

#      - name: Install dependencies
#        run: pip install -r requirements.txt
          
          
        # Parallel installation for speed
      - name: Install system deps & Python deps in parallel
        run: |
        # Start system deps in background
         (sudo apt-get update && sudo apt-get install -y ffmpeg) &
        # Install Python deps while system deps install
         pip install --no-cache-dir -r requirements.txt &
        # Wait for both to complete
         wait


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup environment and secrets
        run: |
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Run upload script
        run: python main.py categories