name: Daily YouTube Upload - Categories

on:
  # 12:30 UTC = 18:00 IST
  schedule:
    # Weekdays: 8 AM, 10 AM, 1 PM, 6 PM IST
    - cron: '30 2,4,7,12 * * 1-5'
    # Weekends: 8 AM, 10 AM, 3 PM, 8 PM IST
    - cron: '30 2,4,9,14 * * 6,0'
  workflow_dispatch:  # Allow manual runs too

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Hindi (Devanagari) fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-unhinted

      - name: Export secret to .env file
        run: echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env

      - name: Restore token.pkl
        run: |
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl

      - name: Write client_secrets.json
        run: |
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Run upload script
        run: python main.py categories
