name: Daily YouTube Upload - Categories US

on:
  # For USA context, 1:00 PM ET → 10:30 PM IST (same day). ET is UTC - 4:00 hours
  schedule:
    # Weekdays: 6:00, 21:00 ET
    - cron: '0 10,1 * * 1-5'
    # Weekends: 11:00, 22:00 ET
    - cron: '0 15,2 * * 6,0'
  workflow_dispatch:  # Allow manual runs too

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup pip cache directory
        run: mkdir -p ~/.cache/pip

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps & Python deps in parallel
        run: |
         (sudo apt-get update && sudo apt-get install -y ffmpeg) &
         pip install -r requirements.txt &
         wait

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup environment and secrets
        run: |
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" > .env
          echo "${{ secrets.TOKEN_PKL_B64 }}" | base64 -d > token.pkl
          echo "${{ secrets.CLIENT_SECRETS_B64 }}" | base64 -d > client_secrets.json

      - name: Run upload script
        run: python main.py categories us